# Generated by Django 4.2.5 on 2023-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='the_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='product')),
                ('price', models.CharField(max_length=60, verbose_name='price')),
                ('pic_sample', models.ImageField(upload_to='images', verbose_name='picture')),
                ('description', models.TextField(verbose_name='description')),
                ('period', models.CharField(choices=[('1', 'one_months'), ('3', 'three_months'), ('6', 'six_months')], max_length=1, verbose_name='period')),
                ('max_users', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1, verbose_name='Users_in_same_time')),
            ],
        ),
    ]
