# Generated by Django 4.2.5 on 2023-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='page_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_pic', models.ImageField(upload_to='images', verbose_name='website_pic')),
            ],
            options={
                'verbose_name': 'website_pic',
                'verbose_name_plural': 'website_pic',
            },
        ),
    ]
