# Generated by Django 4.2.8 on 2024-04-05 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='theproduct',
            name='final_price',
            field=models.IntegerField(default=1, verbose_name='final_price'),
            preserve_default=False,
        ),
    ]
