# Generated by Django 4.2.11 on 2024-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_theproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='price'),
        ),
    ]
