# Generated by Django 4.2.5 on 2023-09-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_the_product_max_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', 'one_months'), ('3', 'three_months'), ('6', 'six_months')], max_length=1, verbose_name='period')),
                ('max_users', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1, verbose_name='Users_in_same_time')),
                ('price', models.CharField(max_length=60, verbose_name='price')),
            ],
        ),
        migrations.RemoveField(
            model_name='the_product',
            name='price',
        ),
        migrations.DeleteModel(
            name='subscription',
        ),
        migrations.AddField(
            model_name='price_list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='base.the_product'),
        ),
    ]
