# Generated by Django 4.2.5 on 2023-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_price_list_remove_the_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=1, verbose_name='period_based_on_month')),
            ],
        ),
        migrations.CreateModel(
            name='user_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=1, verbose_name='Users_in_same_time')),
            ],
        ),
        migrations.AddField(
            model_name='the_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.DeleteModel(
            name='price_list',
        ),
        migrations.AddField(
            model_name='the_product',
            name='time_limit',
            field=models.ManyToManyField(to='base.time_amount'),
        ),
        migrations.AddField(
            model_name='the_product',
            name='users_amount',
            field=models.ManyToManyField(to='base.user_amount'),
        ),
    ]
