# Generated by Django 4.2.5 on 2023-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_time_amount_user_amount_the_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='the_product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='the_product',
            name='time_limit_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='the_product',
            name='users_amount_prices',
            field=models.JSONField(default=dict),
        ),
    ]
