# Generated by Django 4.2.5 on 2023-09-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_price_the_product_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_product',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='the_product',
            name='time_limit_prices',
        ),
        migrations.RemoveField(
            model_name='the_product',
            name='users_amount_prices',
        ),
        migrations.AddField(
            model_name='the_product',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.time_amount'),
        ),
        migrations.RemoveField(
            model_name='the_product',
            name='users_amount',
        ),
        migrations.AddField(
            model_name='the_product',
            name='users_amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.user_amount'),
        ),
    ]
