# Generated by Django 4.2.5 on 2023-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_the_product_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='the_product',
            name='time_limit_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='the_product',
            name='users_amount_prices',
            field=models.JSONField(default=dict),
        ),
    ]
