# Generated by Django 4.2.11 on 2024-06-28 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cart_cart_product_price_cart_total_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_product_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
