# Generated by Django 4.2.5 on 2023-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_the_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_product',
            name='price',
            field=models.IntegerField(default=50, verbose_name='price'),
        ),
    ]
