# Generated by Django 4.2.11 on 2024-06-28 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
