# Generated by Django 4.2.11 on 2024-06-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_theproduct_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=13, verbose_name='price'),
        ),
    ]
