# Generated by Django 4.2.11 on 2024-06-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_theproduct_final_price_alter_theproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theproduct',
            name='final_price',
        ),
    ]
