# Generated by Django 4.2.11 on 2024-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_theproduct_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
