# Generated by Django 4.2.5 on 2023-10-05 19:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_the_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='product')),
                ('price', models.IntegerField(default=50, verbose_name='price')),
                ('pic_sample', models.ImageField(upload_to='images', verbose_name='picture')),
                ('description', models.TextField(verbose_name='description')),
                ('period', models.CharField(choices=[('1', 'one_months'), ('3', 'three_months'), ('6', 'six_months')], default='1', max_length=1, verbose_name='period')),
                ('max_users', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], default='1', max_length=1, verbose_name='Users_in_same_time')),
                ('availabled_at', models.DateTimeField(auto_now_add=True, verbose_name='availabled_at')),
                ('category', models.ManyToManyField(related_name='category', to='base.product_category', verbose_name='Category')),
            ],
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='the_product',
        ),
    ]
