# Generated by Django 4.2.5 on 2023-10-07 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_theproduct_delete_the_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='theproduct',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='theproduct',
            name='availabled_at',
        ),
        migrations.AddField(
            model_name='theproduct',
            name='availability',
            field=models.CharField(choices=[('a', 'available'), ('u', 'unavailable'), ('c', 'checking_product')], default='u', max_length=1, verbose_name='availability_status'),
        ),
        migrations.AddField(
            model_name='theproduct',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='imported_at'),
            preserve_default=False,
        ),
    ]
