# Generated by Django 4.2.5 on 2023-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ipaddress_producthit_theproduct_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='availability',
            field=models.CharField(choices=[('a', 'available'), ('u', 'unavailable'), ('c', 'checking_product')], default='u', max_length=1),
        ),
    ]
