# Generated by Django 4.2.11 on 2024-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_cart_created_at_cart_deleted_cart_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
