# Generated by Django 4.2.5 on 2023-10-23 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_theproduct_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_name', models.CharField(max_length=50, verbose_name='shop')),
                ('Shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='theproduct',
            name='product_shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.shop'),
        ),
    ]
