# Generated by Django 4.2.11 on 2024-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_cart_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='progress_status',
            field=models.CharField(choices=[('0', 'Refuesed'), ('25', 'In process'), ('50', 'Preparation to ship'), ('75', 'In shipping progress'), ('100', 'Shipped')], default='25', max_length=3),
            preserve_default=False,
        ),
    ]
