# Generated by Django 4.2.5 on 2023-11-19 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_shop_theproduct_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Shop_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='theproduct',
            name='product_shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Shop name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id', verbose_name='Shop owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Shop id'),
        ),
    ]
