# Generated by Django 4.2.5 on 2023-11-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_shop_shop_id_remove_shop_shop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='product_shop',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.shop', to_field='shop_id'),
        ),
    ]
