# Generated by Django 4.2.11 on 2024-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_cart_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='progress_status',
        ),
        migrations.CreateModel(
            name='CartsShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('0', 'Refuesed'), ('25', 'In process'), ('50', 'Preparation to ship'), ('75', 'In shipping progress'), ('100', 'Shipped')], max_length=3)),
                ('additional_explanation', models.TextField()),
                ('shipping_carts', models.ManyToManyField(related_name='shipping_carts', to='base.cart')),
            ],
        ),
    ]
