# Generated by Django 4.2.11 on 2024-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_cart_progress_status_cartsshippingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsshippingstatus',
            name='additional_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
