# Generated by Django 4.2.11 on 2024-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_cartsshippingstatus_additional_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsshippingstatus',
            name='progress_status',
            field=models.CharField(choices=[('0', 'Not in progress yet'), ('25', 'In process'), ('50', 'Preparation to ship'), ('75', 'In shipping progress'), ('100', 'Shipped')], max_length=3),
        ),
    ]
