# Generated by Django 4.2.5 on 2023-11-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_theproduct_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theproduct',
            name='product_shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
