# Generated by Django 4.2.11 on 2024-07-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_cart_progress_status_delete_cartsshippingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='theproduct',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='progress_status',
            field=models.CharField(choices=[('00', 'Refuesed'), ('25', 'In process'), ('50', 'Preparation to ship'), ('75', 'In shipping progress'), ('100', 'Shipped')], max_length=3),
        ),
    ]
