# Generated by Django 4.2.11 on 2024-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_theproduct_quantity_theproduct_sold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='progress_status',
            field=models.CharField(choices=[('00', 'Refuesed'), ('25', 'In process'), ('50', 'Preparation to ship'), ('75', 'In shipping progress'), ('100', 'Shipped')], default='25', max_length=3),
        ),
    ]
