# Generated by Django 4.2.8 on 2024-01-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_theproduct_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable'), ('I', 'Investigate')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='theproduct',
            name='max_users',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default='1', max_length=1, verbose_name='Users_in_same_time'),
        ),
        migrations.AlterField(
            model_name='theproduct',
            name='period',
            field=models.CharField(choices=[('1', 'One_months'), ('3', 'Three_months'), ('6', 'Six_months')], default='1', max_length=1, verbose_name='period'),
        ),
    ]
