# Generated by Django 4.2.8 on 2024-01-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_theproduct_taggings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theproduct',
            old_name='taggings',
            new_name='tags',
        ),
    ]
