# Generated by Django 4.2.11 on 2024-07-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theproduct',
            old_name='imported_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='theproduct',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='theproduct',
            name='period',
        ),
    ]
