# Generated by Django 4.2.11 on 2024-07-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_imported_at_theproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='specs',
            field=models.JSONField(default='', verbose_name='Specifications'),
            preserve_default=False,
        ),
    ]
