# Generated by Django 4.2.8 on 2024-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_taggings_theproduct_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable'), ('I', 'Investigate'), ('B', 'Banned')], default='I', max_length=1, verbose_name='Status'),
        ),
    ]
