# Generated by Django 4.2.11 on 2024-07-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_theproduct_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theproduct',
            name='pic_sample',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images', verbose_name='picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='base.theproduct')),
            ],
        ),
    ]
