# Generated by Django 4.2.11 on 2024-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_theproduct_pic_sample_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='thumbnail',
            field=models.ImageField(default=None, help_text='This picture will be shown to the user in list pages', upload_to='images/thumbnail'),
            preserve_default=False,
        ),
    ]
