# Generated by Django 4.2.8 on 2024-02-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='page_pic',
            new_name='PagePic',
        ),
        migrations.RenameModel(
            old_name='product_category',
            new_name='ProductCategory',
        ),
    ]
