# Generated by Django 4.2.11 on 2024-07-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_theproduct_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theproduct',
            old_name='thumbnail',
            new_name='pic_sample',
        ),
    ]
