# Generated by Django 4.2.11 on 2024-08-03 08:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='color'),
        ),
    ]
