# Generated by Django 4.2.5 on 2023-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='09', max_length=11, unique=True, verbose_name='phone_number'),
        ),
    ]
