# Generated by Django 4.2.5 on 2023-09-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_mobile_number_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
