# Generated by Django 4.2.11 on 2024-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
