# Generated by Django 4.2.5 on 2023-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usersellerinfo_admin_reject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_description',
        ),
        migrations.AddField(
            model_name='usersellerinfo',
            name='user_description',
            field=models.TextField(blank=True, help_text='Any descriptions (optional)'),
        ),
    ]
