# Generated by Django 4.2.11 on 2024-08-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_reportedproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersellerinfo',
            name='investigated',
            field=models.BooleanField(default=False),
        ),
    ]
