# Generated by Django 4.2.5 on 2023-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='review_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_reject_reason',
            field=models.TextField(default='Not reviewed yet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.CharField(choices=[('N', 'Not accepted'), ('I', 'Investigate'), ('A', 'Accepted')], default='N', max_length=1, verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='usersellerinfo',
            name='national_code',
            field=models.CharField(help_text='Your National Code must be 10 digits', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usersellerinfo',
            name='user_id',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
