# Generated by Django 4.2.5 on 2023-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_created_at_remove_user_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/user_profile'),
        ),
    ]
