# Generated by Django 4.2.5 on 2023-11-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_nick_name_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
