# Generated by Django 4.2.5 on 2023-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_nick_name_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='/static/noun-user-avatar-2540366.png', null=True, upload_to='media/user_profile'),
        ),
    ]
