# Generated by Django 4.2.8 on 2024-01-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_email_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_reject_reason',
        ),
    ]
