# Generated by Django 4.2.8 on 2024-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_reportedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedproduct',
            name='checked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
