# Generated by Django 4.2.8 on 2024-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_reportedproduct_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedproduct',
            name='product_id',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportedproduct',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
