# Generated by Django 4.2.8 on 2024-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_reportedproduct_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='reportedproduct',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Investigated'),
        ),
        migrations.AlterField(
            model_name='reportedproduct',
            name='product_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
